config/routes.rb
require 'sidekiq/web'

GitlabCi::Application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status
      get :charts
      get :integration
      post :build
    end

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :runner_projects
  end

  resource :user_sessions
  resources :runners, only: [:index, :update, :destroy] do
    member do
      put :assign_all
    end
  end

  root :to => 'projects#index'
end

app/models/build.rb
# == Schema Information
#
# Table name: builds
#
#  id          :integer          not null, primary key
#  project_id  :integer
#  ref         :string(255)
#  status      :string(255)
#  finished_at :datetime
#  trace       :text(2147483647)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  sha         :string(255)
#  started_at  :datetime
#  tmp_file    :string(255)
#  before_sha  :string(255)
#  push_data   :text
#  runner_id   :integer
#

class Build < ActiveRecord::Base
  belongs_to :project
  belongs_to :runner

  serialize :push_data

  attr_accessible :project_id, :ref, :sha, :before_sha,
    :status, :finished_at, :trace, :started_at, :push_data, :runner_id

  validates :sha, presence: true
  validates :ref, presence: true
  validates :status, presence: true

  scope :running, ->() { where(status: "running") }
  scope :pending, ->() { where(status: "pending") }
  scope :success, ->() { where(status: "success") }
  scope :failed, ->() { where(status: "failed")  }
  scope :uniq_sha, ->() { select('DISTINCT(sha)') }

  def self.last_month
    where('created_at > ?', Date.today - 1.month)
  end

  def self.create_from(build)
    new_build = build.dup
    new_build.status = :pending
    new_build.save
  end

  state_machine :status, initial: :pending do
    event :run do
      transition pending: :running
    end

    event :drop do
      transition running: :failed
    end

    event :success do
      transition running: :success
    end

    event :cancel do
      transition [:pending, :running] => :canceled
    end

    after_transition :pending => :running do |build, transition|
      build.update_attributes started_at: Time.now
    end

    after_transition any => [:success, :failed, :canceled] do |build, transition|
      build.update_attributes finished_at: Time.now
    end

    state :pending, value: 'pending'
    state :running, value: 'running'
    state :failed, value: 'failed'
    state :success, value: 'success'
    state :canceled, value: 'canceled'
  end

  def compare?
    gitlab? && before_sha
  end

  def gitlab?
    project.gitlab?
  end

  def ci_skip?
    !!(git_commit_message =~ /(\[ci skip\])/)
  end

  def git_author_name
    commit_data[:author][:name] if commit_data && commit_data[:author]
  end

  def git_commit_message
    commit_data[:message] if commit_data
  end

  def short_before_sha
    before_sha[0..8]
  end

  def short_sha
    sha[0..8]
  end

  def trace_html
    html = Ansi2html::convert(trace) if trace.present?
    html ||= ''
  end

  def to_param
    sha
  end

  def started?
    !pending? && !canceled? && started_at
  end

  def active?
    running? || pending?
  end

  def commands
    project.scripts
  end

  def commit_data
    push_data[:commits].each do |commit|
      return commit if commit[:id] == sha
    end
  rescue
    nil
  end

  def repo_url
    project.ssh_url_to_repo
  end
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_filter :authenticate_user!, except: [:status]
  before_filter :project
  before_filter :authorize_access_project!, except: [:status]

  def show
    @builds = builds

    @build = if params[:bid]
               @builds.where(id: params[:bid])
             else
               @builds
             end.limit(1).first


    raise ActiveRecord::RecordNotFound unless @build

    @builds = @builds.page(params[:page]).per(20)
  end

  def retry
    @build = builds.limit(1).first

    build = project.builds.create(
      sha: @build.sha,
      before_sha: @build.before_sha,
      push_data: @build.push_data,
      ref: @build.ref
    )

    redirect_to project_build_path(project, build)
  end

  def status
    @build = builds.limit(1).first

    render json: @build.to_json(only: [:status, :id, :sha])
  end

  def cancel
    @build = @project.builds.find(params[:id])
    @build.cancel

    redirect_to project_build_path(@project, @build)
  end

  protected

  def project
    @project = Project.find(params[:project_id])
  end

  def builds
    project.builds.where(sha: params[:id]).order('id DESC')
  end
end

app/helpers/builds_helper.rb
module BuildsHelper
  def build_duration build
    if build.started?
      from = build.started_at
      to = build.finished_at || Time.zone.now
      distance_of_time_in_words(from, to)
    end
  end

  def build_ref_link build
    if build.gitlab?
      gitlab_ref_link build.project, build.ref
    else
      build.ref
    end
  end

  def build_compare_link build
    if build.gitlab?
      gitlab_compare_link build.project, build.short_before_sha, build.short_sha
    end
  end

  def build_commit_link build
    if build.gitlab?
      gitlab_commit_link build.project, build.short_sha
    else
      build.short_sha
    end
  end

  def build_link build
    link_to(build.short_sha, project_build_path(build.project, build))
  end
end

app/views/builds/_build.html.haml
%tr.build.alert{class: build_status_alert_class(build)}
  %td.status
    = build.status

  %td.build-link
    = link_to project_build_path(@project, build) do
      %strong #{build.short_sha}

  %td.build-message
    %span= truncate(build.git_commit_message, length: 50)

  %td.build-branch
    - unless @ref
      %span= build.ref

  %td.duration
    = build_duration build

  %td.timestamp
    - if build.finished_at
      %span #{time_ago_in_words build.finished_at} ago

app/views/builds/show.html.haml
%h3
  Project: #{@project.name}
  .right
    %a.btn.btn-small{href: edit_project_path(@project)}
      %i.icon-edit.icon-white
      Edit Project

%p
  = link_to project_path(@project) do
    &larr; Back to project builds
%hr
.row-fluid
  .span9
    .alert{class: build_status_alert_class(@build)}
      %h4
        Build ##{@build.short_sha}
        %small= "(#{@build.ref})"
      .right
        %span= @build.updated_at.stamp('19:00 Aug 27')
      = @build.status


    .row-fluid
      .span6
        %fieldset
          %legend
            Build
            .right
              - if @build.active?
                = link_to "Cancel", cancel_project_build_path(@project, @build.id), class: 'btn btn-small btn-danger'
              - else
                = link_to "Retry", retry_project_build_path(@project, @build.sha), class: 'btn btn-small', method: :post

          %p
            %b Status:
            #{@build.status}
          - if @build.started_at
            %p
              %b Duration:
              #{build_duration @build}
          - if @build.finished_at
            %p
              %b Finished:
              #{time_ago_in_words(@build.finished_at)} ago
          %p
            %b Runner:
            - if @build.runner
              = @build.runner.token
      .span6
        %fieldset
          %legend Commit
          %p
            %b ID:
            #{build_commit_link @build}
          - if @build.compare?
            %p
              %b Compare:
              #{build_compare_link @build}
          %p
            %b Branch:
            #{build_ref_link @build}
          %p
            %b Author:
            #{@build.git_author_name}
          %p
            %b Message:
            #{@build.git_commit_message}

    .clearfix
    - if @build.active?
      .autoscroll-container.pull-right
        %button.btn.btn-mini#autoscroll-button{:type => "button", :data => {:state => 'disabled'}} enable autoscroll
      .clearfix
    %pre.trace#build-trace
      = preserve do
        = raw @build.trace_html

  .span3
    .builds
      %h5 Builds for #{@build.short_sha}:
      %table.builds
        %thead
          %tr
            %th Build ID
            %th Status
        - @builds.each_with_index do |build, i|
          %tr.build.alert{class: build_status_alert_class(build)}
            %td
              = link_to project_build_path(@project, build, bid: build.id ) do
                %span #{i+=1} &ndash; #{build.short_sha}
            %td.status= build.status


      = paginate @builds
%br
.right
  %a.btn.btn-small{href: edit_project_path(@project)}
    %i.icon-edit.icon-white
    Edit Project


- if @build.active?
  :javascript
    $(function(){
      getBuild('#{project_build_path(@project, @build)}', '#{@build.id}');
    })

app/views/builds/show.js.haml
- if @build.running?
  :plain
    $('#build-trace').html("#{escape_javascript(@build.trace_html)}");
    $('#build-trace').append('#{loader_html}');
    checkAutoscroll();
    getBuild('#{project_build_path(@project, @build)}', '#{@build.id}');
- else
  :plain
    location.href = "#{project_build_path(@project, @build)}";