config/routes.rb
require 'sidekiq/web'

GitlabCi::Application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status
      get :charts
      get :integration
      post :build
    end

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :runner_projects
  end

  resource :user_sessions
  resources :runners, only: [:index, :update, :destroy] do
    member do
      put :assign_all
    end
  end

  root :to => 'projects#index'
end

app/models/runner.rb
# == Schema Information
#
# Table name: runners
#
#  id          :integer          not null, primary key
#  token       :string(255)
#  public_key  :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :string(255)
#

class Runner < ActiveRecord::Base
  has_many :builds
  has_many :runner_projects, dependent: :destroy
  has_many :projects, through: :runner_projects

  has_one :last_build, class_name: 'Build', order: 'id DESC'

  attr_accessible :token, :public_key, :description

  before_validation :set_default_values

  def set_default_values
    self.token = SecureRandom.hex(15) if self.token.blank?
  end

  def assign_to(project, current_user)
    ActiveRecord::Base.transaction do
      runner_project = project.runner_projects.create!(runner_id: self.id)

      opts = {
        key: self.public_key,
        title: "gitlab-ci-runner-#{self.id}",
        private_token: current_user.private_token
      }

      result = Network.new.add_deploy_key(current_user.url, project.gitlab_id, opts)
      raise "Can't add deploy key" unless result
      true
    end
  rescue => ex
    logger.warn "Assign runner to project failed: #{ex}"
    false
  end

  def display_name
    return token unless !description.blank?

    description
  end
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :runner, except: :index

  def index
    @runners = Runner.page(params[:page]).per(30)
  end

  def update
    @runner.update_attributes(description: params[:runner][:description])

    respond_to do |format|
      format.js
      format.html { redirect_to runners_path }
    end
  end

  def destroy
    Runner.find(params[:id]).destroy

    redirect_to runners_path
  end

  def assign_all
    Project.all.each { |project| @runner.assign_to(project, current_user) }

    respond_to do |format|
      format.js
      format.html { redirect_to runners_path, notice: "Runner was assigned to all projects" }
    end
  end

  private

  def runner
    @runner ||= Runner.find(params[:id])
  end
end

app/views/runners/_runner.html.haml
%tr{id: dom_id(runner)}
  %td
    %span.badge.badge-info= runner.id
  %td
    = runner.token
  %td
    .runner-description
      = runner.description
      %span (#{link_to 'edit', '#', class: 'edit-runner-link'})
    .runner-description-form.hide
      = form_for runner, remote: true do |f|
        = f.text_field :description, class: 'pull-left'
        = f.submit 'Save', class: 'btn'
  %td
    - last_build = runner.last_build
    - if last_build
      = link_to last_build.short_sha, [last_build.project, last_build]
    - else
      unknown
  %td
    = runner.projects.count
  %td
    %span.badge.badge-success
      #{runner.builds.success.count}
    %span /
    %span.badge.badge-important
      #{runner.builds.failed.count}
  %td
    #{time_ago_in_words(runner.created_at)} ago
  %td
    .pull-right
      = link_to 'Assign to all', assign_all_runner_path(runner), class: 'btn btn-small assign-all-runner', title: 'Assign runner to all projects', method: :put, remote: true
      = link_to 'Remove', runner, data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger btn-small'

app/views/runners/assign_all.js.haml
:plain
  $("#runner_#{@runner.id}").replaceWith("#{escape_javascript(render(@runner))}")

app/views/runners/index.html.haml
= content_for :title do
  %h3.project-title
    Runners

.alert.alert-info
  %strong To register new runner you should use next token
  %code #{GitlabCi::RunnersToken}

%p
  Runner is a process which run a build.
  You can setup as much runners as you need.
  %br
  Runners can be placed on separate users, servers,  even on your local machine
  %br

%table.table
  %tr
    %th ID
    %th Token
    %th Description
    %th Last build
    %th Projects
    %th Builds Stats
    %th Registered
    %th

  = render @runners
  = paginate @runners

app/views/runners/update.js.haml
:plain
  $("#runner_#{@runner.id}").replaceWith("#{escape_javascript(render(@runner))}")