config/routes.rb
require 'sidekiq/web'

GitlabCi::Application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status
      get :charts
      get :integration
      post :build
    end

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :runner_projects
  end

  resource :user_sessions
  resources :runners, only: [:index, :update, :destroy] do
    member do
      put :assign_all
    end
  end

  root :to => 'projects#index'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id               :integer          not null, primary key
#  name             :string(255)      not null
#  timeout          :integer          default(1800), not null
#  scripts          :text             default(""), not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  token            :string(255)
#  default_ref      :string(255)
#  gitlab_url       :string(255)
#  always_build     :boolean          default(FALSE), not null
#  polling_interval :integer
#  public           :boolean          default(FALSE), not null
#  ssh_url_to_repo  :string(255)
#  gitlab_id        :integer
#

class Project < ActiveRecord::Base
  attr_accessible :name, :path, :scripts, :timeout, :token,
    :default_ref, :gitlab_url, :always_build, :polling_interval,
    :public, :ssh_url_to_repo, :gitlab_id

  has_many :builds, dependent: :destroy
  has_many :runner_projects, dependent: :destroy
  has_many :runners, through: :runner_projects

  #
  # Validations
  #
  validates_presence_of :name, :scripts, :timeout, :token, :default_ref, :gitlab_url, :ssh_url_to_repo, :gitlab_id

  validates_uniqueness_of :name

  validates :polling_interval,
    presence: true,
    if: ->(project) { project.always_build.present? }


  scope :public, where(public: true)

  before_validation :set_default_values

  def self.from_gitlab(user, page, per_page, scope = :owned)
    opts = { private_token: user.private_token }
    opts[:per_page] = per_page if per_page.present?
    opts[:page]     = page     if page.present?

    projects = Network.new.projects(user.url, opts, scope)

    if projects
      projects.map { |pr| OpenStruct.new(pr) }
    else
      []
    end
  end

  def self.already_added?(project)
    where(gitlab_url: project.web_url).any?
  end

  def set_default_values
    self.token = SecureRandom.hex(15) if self.token.blank?
  end

  def register_build(opts={})
    ref = opts[:ref]

    raise 'ref is not defined' unless ref

    if ref.include? 'heads'
      ref = ref.scan(/heads\/(.*)$/).flatten[0]
    end

    before_sha = opts[:before]
    sha = opts[:after]

    data = {
      project_id: self.id,
      ref: ref,
      sha: sha,
      before_sha: before_sha,
      push_data: opts
    }

    @build = Build.create(data)
  end

  def gitlab?
    gitlab_url.present?
  end

  def status
    last_build.status if last_build
  end

  def last_build
    builds.last
  end

  def last_build_date
    last_build.try(:created_at)
  end

  def human_status
    status
  end

  def status_image ref = 'master'
    build = self.builds.where(ref: ref).last
    image_for_build build
  end

  def last_build_for_sha sha
    builds.where(sha: sha).order('id DESC').limit(1).first
  end

  def sha_status_image sha
    build = last_build_for_sha(sha)
    image_for_build build
  end

  def image_for_build build
    return 'unknown.png' unless build

    if build.success?
      'success.png'
    elsif build.failed?
      'failed.png'
    elsif build.active?
      'running.png'
    else
      'unknown.png'
    end
  end

  def tracked_refs
    @tracked_refs ||= default_ref.split(",").map{|ref| ref.strip}
  end

  def valid_token? token
    self.token && self.token == token
  end

  def no_running_builds?
    # Get running builds not later than 3 days ago to ignore hangs
    builds.running.where("updated_at > ?", 3.days.ago).empty?
  end
end


# == Schema Information
#
# Table name: projects
#
#  id          :integer(4)      not null, primary key
#  name        :string(255)     not null
#  path        :string(255)     not null
#  timeout     :integer(4)      default(1800), not null
#  scripts     :text            default(""), not null
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#  token       :string(255)
#  default_ref :string(255)
#

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:build, :status, :index, :show]
  before_filter :project, only: [:build, :integration, :show, :status, :edit, :update, :destroy, :charts]
  before_filter :authorize_access_project!, except: [:build, :gitlab, :status, :index, :show, :new, :create]
  before_filter :authenticate_token!, only: [:build]
  before_filter :no_cache, only: [:status]

  layout 'project', except: [:index, :gitlab]

  def index
    @projects = Project.public.page(params[:page]) unless current_user
  end

  def gitlab
    current_user.reset_cache if params[:reset_cache]
    @page = (params[:page] || 1).to_i
    @per_page = 100
    @gl_projects = current_user.gitlab_projects(@page, @per_page)
    @projects = Project.where(gitlab_id: @gl_projects.map(&:id)).order('name ASC')
    @total_count = @gl_projects.size
    @gl_projects.reject! { |gl_project| @projects.map(&:gitlab_id).include?(gl_project.id) }
  rescue
    @error = 'Failed to fetch GitLab projects'
  end

  def show
    unless @project.public
      authenticate_user!
      authorize_access_project!
    end

    @ref = params[:ref]

    @builds = @project.builds
    @builds = @builds.where(ref: @ref) if @ref
    @builds = @builds.order('id DESC').page(params[:page]).per(20)
  end

  def integration
  end

  def create
    project = YAML.load(params[:project])

    params = {
      name: project.name_with_namespace,
      gitlab_id: project.id,
      gitlab_url: project.web_url,
      scripts: 'ls -la',
      default_ref: project.default_branch || 'master',
      ssh_url_to_repo: project.ssh_url_to_repo
    }

    @project = Project.new(params)

    if @project.save
      redirect_to project_path(@project, show_guide: true), notice: 'Project was successfully created.'
    else
      redirect_to :back, alert: 'Cannot save project'
    end
  end

  def edit
  end

  def update
    if project.update_attributes(params[:project])
      redirect_to project, notice: 'Project was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    project.destroy

    redirect_to projects_url
  end

  def build
   # Ignore remove branch push
   return head(200) if params[:after] =~ /^00000000/

   # Support payload (like github) push
   build_params = if params[:payload]
                    HashWithIndifferentAccess.new(JSON.parse(params[:payload]))
                  else
                    params
                  end.dup

   @build = @project.register_build(build_params)

   if @build
     head 200
   else
     head 500
   end
  rescue
    head 500
  end

  # Project status badge
  # Image with build status for sha or ref
  def status
    image_name = if params[:sha]
                   @project.sha_status_image(params[:sha])
                 elsif params[:ref]
                   @project.status_image(params[:ref])
                 else
                   'unknown.png'
                 end

    send_file Rails.root.join('public', image_name), filename: image_name, disposition: 'inline'
  end

  def charts
    @charts = {}
    @charts[:week] = Charts::WeekChart.new(@project)
    @charts[:month] = Charts::MonthChart.new(@project)
    @charts[:year] = Charts::YearChart.new(@project)
  end


  protected

  def project
    @project ||= Project.find(params[:id])
  end

  def no_cache
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_statuc_class(project)
    if project.last_build.try :success?
      'alert-success'
    elsif project.last_build.try :failed?
      'alert-error'
    else
      ''
    end
  end

  def build_status_alert_class build
    if build.success?
      'alert-success'
    elsif build.failed? || build.canceled?
      'alert-error'
    else
      ''
    end
  end

  def ref_tab_class ref = nil
    'active' if ref == @ref
  end

  def success_ratio(success_builds, failed_builds)
    failed_builds = failed_builds.count
    success_builds = success_builds.count

    return 100 if failed_builds.zero?

    ratio = (success_builds.to_f / (success_builds + failed_builds)) * 100
    ratio.to_i
  end

  def markdown_badge_code(project, ref)
    url = status_project_url(project, ref: ref, format: 'png')
    "[![build status](#{url})](#{project_url(project, ref: ref)})"
  end

  def html_badge_code(project, ref)
    url = status_project_url(project, ref: ref, format: 'png')
    "<a href='#{project_url(project, ref: ref)}'><img src='#{url}' /></a>"
  end
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %p.lead= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      .alert.alert-error
        %ul
          - @project.errors.full_messages.each do |msg|
            %li= msg

  .row-fluid
    .span7
      %fieldset
        %legend Build
        .field
          = f.label :timeout, 'Timeout (in seconds) per command'
          = f.number_field :timeout, class: 'input-xlarge'
        .field
          = f.label :scripts
          = f.text_area :scripts, class: 'input-xxlarge', rows: 11, placeholder: "bundle exec rake spec"


      %fieldset
        %legend Build Schedule
        .field
          = f.label :always_build do
            = f.check_box :always_build
            %span Enable automatic build on schedule
        %br
        .field
          = f.label :polling_interval, "Build interval"
          = f.number_field :polling_interval, placeholder: '5'
          %span Hours
    .span5
      %fieldset
        %legend Project settings
        .field
          = f.label :default_ref, "Make tabs for next branches"
          = f.text_field :default_ref, class: 'input-xlarge', placeholder: 'master, stable'
          %p You will be able to filter builds by following branches
        .field.alert
          = f.label :public do
            = f.check_box :public, class: 'input-xlarge'
            %span Public (Anyone can see project and builds list)
        %br
      %fieldset
        %legend Advanced settings
        .field
          = f.label :name
          = f.text_field :name, class: 'input-xlarge', placeholder: 'my-project'
        .field
          = f.label :gitlab_url, "GitLab url to project"
          = f.text_field :gitlab_url, class: 'input-xlarge', placeholder: 'http://gitlab.domain.com/project-slug'
        .field
          = f.label :gitlab_id, "GitLab project id"
          = f.text_field :gitlab_id, class: 'input-xlarge', placeholder: '17'
        .field
          = f.label :ssh_url_to_repo, "ssh url to repository"
          = f.text_field :ssh_url_to_repo, class: 'input-xlarge', placeholder: 'git@gitlab.domain.com:project-slug.git'
        .field
          = f.label :token, "Token (Leave empty to generate random token)"
          = f.text_field :token, class: 'input-xlarge', placeholder: 'xEeFCaDAB89'

  .form-actions
    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Cancel', projects_path, class: 'btn'
    - unless @project.new_record?
      = link_to 'Remove Project', project_path(@project), method: :delete, confirm: 'Project will be removed. Are you sure?', class: 'btn btn-danger right'

app/views/projects/_gitlab.html.haml
.clearfix.light
  .pull-left.fetch-status
    Fetched from GitLab (#{link_to current_user.url, current_user.url}) #{time_ago_in_words(current_user.sync_at)} ago.
    = link_to gitlab_projects_path(reset_cache: true), remote: true, class: 'sync-now btn btn-mini' do
      %i.icon-refresh
      Sync now
    %br

  .pull-right
    #{@total_count} projects, #{@projects.size} of them added to CI
%br

%table.table
  %tr
    %th ID
    %th Name
    %th Last build
    %th Access
    %th Builds
    %th Runners

  = render @projects

  - @gl_projects.sort_by(&:name_with_namespace).each do |project|
    %tr.light
      %td
        \-
      %td
        = project.name_with_namespace
        -#= link_to project.web_url, project.web_url
      %td
        %small Not added to CI
      %td
      %td
      %td
        - if Project.already_added?(project)
          %strong.cgreen
            Added
        - else
          = form_tag projects_path do
            = hidden_field_tag :project, project.to_yaml
            = submit_tag 'Add', class: 'btn btn-small'

%center
  - if @page > 1
    = link_to gitlab_projects_path(page: @page - 1), class: 'btn', remote: true do
      %i.icon-angle-left
      prev
  &nbsp;
  - if @total_count == @per_page
    = link_to gitlab_projects_path(page: @page + 1), class: 'btn', remote: true do
      next
      %i.icon-angle-right

app/views/projects/_project.html.haml
- last_build = project.last_build
%tr.alert{class: project_statuc_class(project) }
  %td
    = project.id
  %td
    = link_to project do
      %strong= project.name
  %td
    - if last_build
      #{last_build.status} (#{build_link(last_build)})
      = time_ago_in_words project.last_build_date
      ago
    - else
      No builds yet
  %td
    - if project.public
      %i.icon-globe
      Public
    - else
      %i.icon-lock
      Private
  %td
    = project.builds.count
  %td
    - count = project.runners.count
    - if count.zero?
      %span.badge.badge-important= count
    - else
      %span.badge.badge-success= count
  -#%td
    - if current_user
      %a{href: edit_project_path(project)}
        %i.icon-edit.icon-white
        Edit

app/views/projects/_public.html.haml
= content_for :title do
  %h3.project-title
    Public projects
.projects
  %table.table
    %tr
      %th ID
      %th Name
      %th Last build
      %th Access
      %th Builds
      %th Runners
    = render @projects
= paginate @projects

app/views/projects/charts.html.haml
%fieldset
  %legend
    Builds chart for last week
    (#{date_from_to(Date.today - 7.days, Date.today)})

  %canvas#weekChart.padded{width: 800, height: 200}

%fieldset
  %legend
    Builds chart for last month
    (#{date_from_to(Date.today - 30.days, Date.today)})

  %canvas#monthChart.padded{width: 800, height: 300}

%fieldset
  %legend Builds chart for last year
  %canvas#yearChart.padded{width: 800, height: 400}

%fieldset
  %legend Overall
  %p
    Total:
    %strong= pluralize @project.builds.count, 'build'
  %p
    Successful:
    %strong= pluralize @project.builds.success.count, 'build'
  %p
    Failed:
    %strong= pluralize @project.builds.failed.count, 'build'

  %p
    Success ratio:
    %strong
      #{success_ratio(@project.builds.success, @project.builds.failed)}%

  %p
    Commits covered:
    %strong
      = @project.builds.uniq_sha.count

- [:week, :month, :year].each do |scope|
  :javascript
    var data = {
      labels : #{@charts[scope].labels.to_json},
      datasets : [
        {
          fillColor : "rgba(220,220,220,0.5)",
          strokeColor : "rgba(220,220,220,1)",
          pointColor : "rgba(220,220,220,1)",
          pointStrokeColor : "#EEE",
          data : #{@charts[scope].total.to_json}
        },
        {
          fillColor : "#4A3",
          strokeColor : "rgba(151,187,205,1)",
          pointColor : "rgba(151,187,205,1)",
          pointStrokeColor : "#fff",
          data : #{@charts[scope].success.to_json}
        }
      ]
    }
    var ctx = $("##{scope}Chart").get(0).getContext("2d");
    new Chart(ctx).Line(data,{"scaleOverlay": true});

app/views/projects/edit.html.haml
= render 'form'

app/views/projects/gitlab.js.haml
- if @error
  :plain
    $(".projects").html("#{@error}");
- else
  :plain
    $(".projects").html("#{escape_javascript(render("gitlab"))}");

app/views/projects/index.html.haml
- if current_user
  = content_for :title do
    %h3.project-title
      GitLab projects

  .projects
    %p.fetch-status.light
      %i.icon-refresh.icon-spin
      Please wait while we fetch from GitLab (#{current_user.url})
  :javascript
    $.get("#{gitlab_projects_path}")
- else
  = render 'public'

app/views/projects/integration.html.haml
%p.lead Integration with GitLab:

%form.form-horizontal
  %fieldset
    .alert.alert-success
      %legend
        Complete (as service)
        %small
      %p
        Copy to GitLab &rarr; Project &rarr; Services
        (#{link_to 'screenshot', image_path('service_sample.png'), target: '_blank'})
      %ul
        %li build on push
        %li integration with Merge Requests
        %li links to GitLab instance


      .control-group
        = label_tag :token, 'Project Token', class: 'control-label'
        .controls
          = text_field_tag :token, @project.token, class: 'input-xxlarge', readonly: true
      .control-group
        = label_tag :url, 'Project URL', class: 'control-label'
        .controls
          = text_field_tag :url, project_url(@project), class: 'input-xxlarge', readonly: true



  %br
  %fieldset
    .alert.alert-info
      %legend
        Partial (as web hook)
        %small build on push, links to GitLab commits

      %p Copy to GitLab &rarr; Project &rarr; Web Hooks
      %ul
        %li build on push
        %li links to GitLab instance

      .control-group
        = label_tag :hook_url, 'HTTP POST Hook url', class: 'control-label'
        .controls
          = text_field_tag :url, build_project_url(@project, token: @project.token), class: 'input-xxlarge', readonly: true

app/views/projects/new.html.haml
%h3 New project

= link_to projects_path do
  &larr; Back to projects
%hr
= render 'form'

app/views/projects/show.html.haml
= render 'shared/guide' if params[:show_guide].present?


%ul.nav.nav-tabs
  %li{class: ref_tab_class}
    = link_to 'All builds', project_path(@project)
  - @project.tracked_refs.each do |ref|
    %li{class: ref_tab_class(ref)}
      = link_to ref, project_path(@project, ref: ref)


- if @ref
  %p
    Paste build status image for #{@ref} with next link
    = link_to '#', class: 'badge-codes-toggle btn btn-small ' do
      Status Badge
    .badge-codes-block.well.well-small.hide
      %label Markdown:
      = text_field_tag 'badge_md', markdown_badge_code(@project, @ref), readonly: true, class: 'input-xxlarge'
      %label Html:
      = text_field_tag 'badge_html', html_badge_code(@project, @ref), readonly: true, class: 'input-xxlarge'




%table.builds
  %thead
    %tr
      %th Status
      %th Commit
      %th Message
      %th Branch
      %th Duration
      %th Finished at

  = render @builds

= paginate @builds
- if @builds.empty?
  .alert
    No builds yet