config/routes.rb
require 'sidekiq/web'

GitlabCi::Application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status
      get :charts
      get :integration
      post :build
    end

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :runner_projects
  end

  resource :user_sessions
  resources :runners, only: [:index, :update, :destroy] do
    member do
      put :assign_all
    end
  end

  root :to => 'projects#index'
end

app/views/layouts/_foot.html.haml
%hr
.container-fluid
  .pull-right
    %p.light
      GitLab CI
      %span= GitlabCi::Version
      %small= GitlabCi::Revision

app/views/layouts/_head.html.haml
%head
  %meta{charset: "utf-8"}
  %title GitLab CI
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
  = favicon_link_tag 'favicon.ico'

app/views/layouts/_info.html.haml
.container-fluid
  - if alert || notice
    - if alert
      .alert= alert
    - if notice
      .alert.alert-info= notice

  - if current_user
    - if @project && @project.runners.count.zero? && !params[:show_guide]
      .alert.alert-error
        %span You should assign at least one runner to project for processing project builds. Visit #{link_to 'this page', project_runner_projects_path(@project)} to assign runner
    - elsif Runner.count.zero?
      = render 'shared/no_runners'

app/views/layouts/_nav.html.haml
.navbar.navbar-static-top.navbar-ci
  .navbar-inner
    .container-fluid
      = link_to 'GitLab CI', root_path, class: "brand"
      %ul.nav
        - if current_user
          %li
            = link_to runners_path do
              Runners
      %ul.nav.pull-right
        - if current_user
          %li
            = link_to user_sessions_path do
              .profile-holder
                = image_tag gravatar_icon(current_user.email, 24)
                %span= current_user.email
          %li
            = link_to user_sessions_path, class: "logout", method: :delete do
              %i.icon-signout
              Logout
        - else
          %li
            = link_to 'Login', new_user_sessions_path

app/views/layouts/application.html.haml
!!! 5
%html{ lang: "en"}
  = render 'layouts/head'
  %body
    = render 'layouts/nav'
    = render 'layouts/info'
    - if content_for?(:title)
      .container-fluid.container-title
        = yield(:title)
      %hr

    .container-fluid.container-body
      = yield
    = render 'layouts/foot'

app/views/layouts/project.html.haml
!!! 5
%html{ lang: "en"}
  = render 'layouts/head'
  %body
    = render 'layouts/nav'
    = render 'layouts/info'
    .container-fluid
      %h3.project-title
        Project: #{@project.name}
        - if @project.public
          %small
            %i.icon-globe
            Public

        - if @project.gitlab_url.present?
          .pull-right
            = link_to 'View on GitLab', @project.gitlab_url, class: 'btn'
    %hr
    .container-fluid
      .row-fluid
        - if current_user
          .span2
            %ul.nav.nav-tabs.nav-stacked
              = nav_link path: 'projects#show' do
                = link_to project_path(@project) do
                  %i.icon-list-alt
                  Builds
                  %small.pull-right= @project.builds.count
              = nav_link path: 'projects#charts' do
                = link_to charts_project_path(@project) do
                  %i.icon-bar-chart
                  Charts
              = nav_link controller: :runner_projects do
                = link_to project_runner_projects_path(@project) do
                  %i.icon-cog
                  Runners
                  %small.pull-right= @project.runner_projects.count
              = nav_link path: 'projects#integration' do
                = link_to integration_project_path(@project) do
                  %i.icon-wrench
                  Integration
              = nav_link path: 'projects#edit' do
                = link_to edit_project_path(@project) do
                  %i.icon-edit
                  Settings
        .span10
          = yield
    = render 'layouts/foot'